
services:
  pyspark-jupyter:
    build:
      context: .
      dockerfile: pyspark-jupyter/Dockerfile
    container_name: pyspark_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - /logs:/logs
      - ./conf/log4j.properties:/opt/spark/conf/log4j.properties
    environment:
      - SPARK_MODE=local
    restart: unless-stopped
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --ServerApp.iopub_data_rate_limit=10000000 --allow-root --NotebookApp.token='' --NotebookApp.password=''
