
services:
  pyspark-jupyter:
    build:
      context: .
      dockerfile: pyspark-jupyter/Dockerfile
    container_name: pyspark_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - SPARK_MODE=local
    restart: unless-stopped
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
